[font]
size = 12.0

# [font.bold]
# family = "JetBrains Mono"
# style = "Bold"

# [font.italic]
# family = "JetBrains Mono"
# style = "Italic"

# [font.normal]
# family = "JetBrains Mono"
# style = "Regular"

[general]
import = [
    "~/.config/alacritty/gruvbox-dark-akomis.toml"
]

[window]
dynamic_title=true
opacity=0.95